#!/usr/bin/env php
<?php

// change the following paths if necessary
$yiic='/Library/WebServer/Documents/yii/framework/yiic.php';
$config=dirname(__FILE__).'/config/console.php';

require_once($yiic);
